### ISSUE TITLE
Wrong cylinder rotation

### ISSUE THREAD

**Issue by rafamanzo** [curran/renderCyliner#1]
Hi Curran,

First of all thanks for the wonderful code!

I don't know if you still maintain this repository, but I found just one issue while using it: the cylinders were being rendered perpendicular to what I expected.

Fortunately, I could correct by modifying just the line 38 from renderCylinder.c to:

```
glRotatef(ax, -vy, vx, 0.0);
```

If you want to see it working, you can found it here:

https://github.com/rafamanzo/runge-kutta

Thank you again!

**Comment by curran** [comment]
Thanks for your suggestion! I just updated the code as you suggested.
